### ISSUE TITLE
请问我部署的时候这个报ImportError: No module named dnscmd.settings。该如何解呢？

### ISSUE THREAD

**Issue by HRUIZHI** [gujifly/dnscmd#1]
C:\dnscmd>python manage.py makemigrations dnspool
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
364, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
308, in execute
    settings.INSTALLED_APPS
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 56, in __ge
tattr__
    self._setup(name)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 41, in _set
up
    self._wrapped = Settings(settings_module)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 110, in __i
nit__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named dnscmd.settings

**Comment by JokerQueue** [comment]
在项目的每个文件夹下面创建一个名为__init__.py的空文件
