### ISSUE TITLE
ImportError: No module named dnscmd.settings 报错请问怎么处理？

### ISSUE THREAD

**Issue by nchair** [gujifly/dnscmd#2]
执行到这里有警告信息
c:\>pip install mysqlclient-1.3.6-cp27-none-win_amd64.whl
Requirement already satisfied: mysqlclient==1.3.6 from file:///C:/mysqlclient-1.3.6-cp27-none-win_am
d64.whl in c:\python27\lib\site-packages
C:\Python27\lib\site-packages\pip-9.0.1-py2.7.egg\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) exten
sion to TLS is not available on this platform. This may cause the server to present an incorrect TLS
 certificate, which can cause validation failures. You can upgrade to a newer version of Python to s
olve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissi
ngwarning.
  SNIMissingWarning
C:\Python27\lib\site-packages\pip-9.0.1-py2.7.egg\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from
 configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a n
ewer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/la
test/security.html#insecureplatformwarning.
  InsecurePlatformWarning

c:\>pip install simplejson-3.11.1-cp27-cp27m-win_amd64.whl
Requirement already satisfied: simplejson==3.11.1 from file:///C:/simplejson-3.11.1-cp27-cp27m-win_a
md64.whl in c:\python27\lib\site-packages
C:\Python27\lib\site-packages\pip-9.0.1-py2.7.egg\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) exten
sion to TLS is not available on this platform. This may cause the server to present an incorrect TLS
 certificate, which can cause validation failures. You can upgrade to a newer version of Python to s
olve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissi
ngwarning.
  SNIMissingWarning
C:\Python27\lib\site-packages\pip-9.0.1-py2.7.egg\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from
 configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a n
ewer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/la
test/security.html#insecureplatformwarning.
  InsecurePlatformWarning

执行这步报错
c:\dnscmd>python manage.py makemigrations dnspool
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django-1.11.29-py2.7.egg\django\core\management\__init__.py",
line 364, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django-1.11.29-py2.7.egg\django\core\management\__init__.py",
line 308, in execute
    settings.INSTALLED_APPS
  File "C:\Python27\lib\site-packages\django-1.11.29-py2.7.egg\django\conf\__init__.py", line 56, in
 __getattr__
    self._setup(name)
  File "C:\Python27\lib\site-packages\django-1.11.29-py2.7.egg\django\conf\__init__.py", line 41, in
 _setup
    self._wrapped = Settings(settings_module)
  File "C:\Python27\lib\site-packages\django-1.11.29-py2.7.egg\django\conf\__init__.py", line 110, i
n __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named dnscmd.settings

**Comment by JokerQueue** [comment]
在项目的每个文件夹下面创建一个名为__init__.py的空文件
